on:
  workflow_dispatch:
    inputs:
      myInput1:
        required: true
        description: "Test1"
        default: "my input value"
      myInput2:
        required: false
        description: "Test2"
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Output Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      - name: Output conditionally
        run: echo "${{ inputs.myInput2 != '' && inputs.myInput2 || inputs.myInput1 }}"
