on:
  workflow_dispatch:
    inputs:
      myInput1:
        required: true
        description: "Test1"
        default: "my input value"
      myInput2:
        required: false
        description: "Test2"
env:
  ACCOUNT_NUMBER: "number_from_job"

jobs:
  myJob:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Output Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      - name: Output Environment
        run: echo "${{ toJSON(vars.ACCOUNT_NUMBER) }}"
      - name: Output conditionally
        run: echo "${{ inputs.myInput2 != '' && inputs.myInput2 || inputs.myInput1 }}"
  myJobThatCallsAnotherWorkflow:
    uses: blestka/url-shortener-api/.github/workflows/test-wf.yml@main
    with:
      env_var: ${{ env.ACCOUNT_NUMBER }}
      environment: development
